// <auto-generated />
namespace ProjetoBibliotecaDeFilme.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RelacionamentoFilme_Idioma : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelacionamentoFilme_Idioma));
        
        string IMigrationMetadata.Id
        {
            get { return "201708171315168_RelacionamentoFilme_Idioma"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
