// <auto-generated />
namespace ProjetoBibliotecaDeFilme.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RelacionamentoFilme_Genero : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelacionamentoFilme_Genero));
        
        string IMigrationMetadata.Id
        {
            get { return "201708170319294_RelacionamentoFilme_Genero"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
